# Generated by Django 5.0.1 on 2024-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Science Fiction', 'Science Fiction'), ('Politics', 'Politics'), ('Gist', 'Gist')], default='category', max_length=20),
        ),
    ]
